
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { DatabaseWithTables } from './schema';

const SUPABASE_URL = "https://nefaagbbbvfgssxgacly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lZmFhZ2JiYnZmZ3NzeGdhY2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1ODY2NzcsImV4cCI6MjA2MzE2MjY3N30.sMNg5a68enUisyAKd6b4EqDqLkeYNDqjLZb_gCCjHoY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<DatabaseWithTables>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
